// This file was generated via rust macros. Don't modify manually.
export enum FuncEvent {
  GlobalFocusChanged = 'global-focus-changed',
  GlobalMouseMove = 'global-mouse-move',
  HandleLayeredHitboxes = 'handle-layered',
  SystemMonitorsChanged = 'system::monitors-changed',
  SystemLanguagesChanged = 'system::languages-changed',
  SystemNetworksChanged = 'system::networks-changed',
  SystemNetworkShareDevicesChanged = 'system::network-share-devices-changed',
  SystemVolumeChanged = 'system::volume-changed',
  ColorsChanged = 'colors-changed',
  TaskbarOverlaped = 'set-auto-hide',
  TaskbarContainerRefresh = 'taskbar::container-refresh',
  ToolbarOverlaped = 'toolbar-overlaped',
  ToolbarHasMaximizedWindow = 'toolbar-has-maximized-window',
  StateSettingsChanged = 'settings-changed',
  StateTaskbarItemsChanged = 'taskbar-items',
  StateThemesChanged = 'themes',
  StateIconPacksChanged = 'icon-packs',
  StatePerformanceModeChanged = 'state::performance-mode-changed',
  PreviewShow = 'preview::show',
  PreviewHide = 'preview::hide',
  CheckUpdateMessageReceived = 'check-update-message',
  DownloadUpdateMessageReceived = 'download-update-message',
  SystemBluetoothStateChanged = 'system::bluetooth-state-changed',
  SystemBluetoothDevicesChanged = 'system::bluetooth-devices-changed',
  NotificationIconChanged = 'notification-icon-changed',
  AppNotification = 'app-notification',
  GameFullscreenChanged = 'game-fullscreen-changed',
}
